### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Zo-Bro-23** [luisignaciocc/ytmusic-scrobbler-web#11]
The hosted version hasn’t been working for a few days now. Just me or backend trouble?

**Comment by Zo-Bro-23** [comment]
Any updates on this? Waiting for this to start working again :)

**Comment by luisignaciocc** [comment]
Sadly, no. It looks like the YouTube auth endpoint is no longer supported, so you might want to check out this other project instead: https://github.com/luisignaciocc/youtube-music-scrobbler.

**Comment by luisignaciocc** [comment]
Link to the ytmusicapi issue https://github.com/sigma67/ytmusicapi/issues/676

**Comment by luisignaciocc** [comment]
Google is rolling out OAuth integration for YouTube Music, which means that the current project won't work anymore since it relies on that integration. I suggest checking out this other project instead, which lets you scrobble https://github.com/luisignaciocc/youtube-music-scrobbler.
