### ISSUE TITLE
Does the browse endpoint no longer work? 

### ISSUE THREAD

**Issue by sgopalan98** [luisignaciocc/ytmusic-scrobbler-web#9]
I seem to get 404 on the browse endpoint. Did YTM deprecate this endpoint? Any thoughts on this?

**Comment by luisignaciocc** [comment]
Yeah, there's an issue with the YouTube integration, but I haven't had the chance to look into it yet.

**Comment by luisignaciocc** [comment]
Google is rolling out OAuth integration for YouTube Music, which means that the current project won't work anymore since it relies on that integration. I suggest checking out this other project instead, which lets you scrobble https://github.com/luisignaciocc/youtube-music-scrobbler.
